import{a as p,i as d,S as m}from"./assets/vendor-u8rapaCG.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&t(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const u="45735019-5668e0368fbdb80eca42c52b3",f="https://pixabay.com/api/",y=async o=>{try{return(await p.get(f,{params:{key:u,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch{throw new Error("Failed to fetch images")}},i=o=>{d.error({title:"Error",message:o})},g=o=>{d.warning({title:"No results",message:o})},h=(o,n)=>{o.forEach(t=>{const e=document.createElement("a");e.classList.add("card"),e.href=t.largeImageURL,e.dataset.caption=`
            <p>Likes: ${t.likes}</p>
            <p>Views: ${t.views}</p>
            <p>Comments: ${t.comments}</p>
            <p>Downloads: ${t.downloads}</p>
        `,e.innerHTML=`
            <img src="${t.webformatURL}" alt="${t.tags}">
            <div class="card-info">${t.tags}</div>
        `,n.appendChild(e)}),new m(".gallery a",{captionsData:"data-caption",captionDelay:250}).refresh()},b=document.getElementById("search-form"),w=document.getElementById("search-input"),c=document.getElementById("gallery"),l=document.getElementById("loading");b.addEventListener("submit",async o=>{o.preventDefault();const n=w.value.trim();if(!n){i("Search field cannot be empty!");return}l.style.display="block",c.innerHTML="";try{const a=await y(n);a.length===0?g("Sorry, there are no images matching your search query. Please try again!"):h(a,c)}catch{i("Something went wrong. Please try again later.")}finally{l.style.display="none"}});
//# sourceMappingURL=index.js.map
